"""Initial Migration

Revision ID: f5643c85823e
Revises: b27e3358d764
Create Date: 2019-09-29 13:00:17.605099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5643c85823e'
down_revision = 'b27e3358d764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
